### ISSUE TITLE
Bughunt-1.0 "Part Design" Linear Array       preview

### ISSUE THREAD

**Issue by free777cat** [Ondsel-Development/FreeCAD#113] opened 2024-07-07 07:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

lack of preview interferes with work
![Зняток екрана як 2024-07-07 10-21-10](https://github.com/Ondsel-Development/FreeCAD/assets/149939500/434f7ec5-3f8d-4ad4-aa95-851b26dd4d48)
![Зняток екрана як 2024-07-07 10-21-49](https://github.com/Ondsel-Development/FreeCAD/assets/149939500/c775ff39-1df9-4898-97d1-9126d69650f4)
![Зняток екрана як 2024-07-07 10-23-06](https://github.com/Ondsel-Development/FreeCAD/assets/149939500/0d1e8c89-34f4-4d81-8503-ac8f45b62909)

now it is not visible

![Зняток екрана як 2024-07-07 10-24-36](https://github.com/Ondsel-Development/FreeCAD/assets/149939500/b9dbc91e-e334-4fe9-b50d-73a2c9acab7a)
![Зняток екрана як 2024-07-07 10-25-10](https://github.com/Ondsel-Development/FreeCAD/assets/149939500/c6690257-7f1c-4d62-a4f4-b71ef02f12ad)

### Full version info

```shell
OS: Linux Mint 22 (MATE/mate)
Word size of Ondsel: 64-bit
Version: 2024.2.0dev.38021 (Git) AppImage
Build type: Release
Branch: flavor
Hash: a34043c4fa4efa3c871e376a4e1536dcdeb86ebc
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Ukrainian/Ukraine (uk_UA)
Installed mods: 
  * Ondsel-Lens 2024.1.22.01 (Disabled)
  * sheetmetal 0.4.21
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by free777cat** [comment] 2024-07-07 07:45
![Зняток екрана як 2024-07-07 10-23-06](https://github.com/Ondsel-Development/FreeCAD/assets/149939500/aac3689c-8e18-4410-97b9-7b7d2e65305e)

**Comment by prokoudine** [comment] 2024-07-07 15:06
I'm sorry, it's hard to say just from the report what the issue is. Sounds like the "Show preview" checkbox ("Оновити вигляд") is available, but... It doesn't work sometimes? Or is not enabled by default? Could you please elaborate?

**Comment by free777cat** [comment] 2024-07-07 15:33
Unfortunately, there is no flag at all. "Show preview" 

The first two photos are how the "preview" works in "realthunder".

"Update view" is another function
![Зняток екрана як 2024-07-07 18-22-51](https://github.com/Ondsel-Development/FreeCAD/assets/149939500/8521b190-d13a-4f8e-be7c-6aabd8833897)

**Comment by prokoudine** [comment] 2024-07-07 16:27
Thank you, so this is more of a request to port from RT's fork?

**Comment by free777cat** [comment] 2024-07-07 17:37
This is a very convenient visualization. The lack of visualization can probably also be considered a "bug". And how to implement it programmatically, you are more experienced.

**Comment by sliptonic** [comment] 2024-07-19 22:30
Looks like a cool feature.  We can add it to the list of RT features to consider porting to FC.  
@prokoudine please add a link to this issue to the document. 

Not a bughunt issue though since behavior is correct as currently designed.  I'm closing the issue otherwise to keep the tracker clean but we will consider porting RTs feature as time permits.

**Closed by sliptonic** 2024-07-19 22:30 UTC
